-- ==============================================================================
-- LOCALEATS PLATFORM: CLEAN DATABASE BOOTSTRAP SCRIPT
-- Run this script in your new Supabase project's SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 0. Enable PostGIS for geospatial capabilities
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. SHOPS TABLE
CREATE TABLE IF NOT EXISTS public.shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  is_active BOOLEAN DEFAULT true,
  lat NUMERIC,
  lng NUMERIC,
  delivery_fee NUMERIC DEFAULT 15.00,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. MENU ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0.00,
  description TEXT,
  category TEXT DEFAULT 'General',
  image_url TEXT,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. RIDER PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.rider_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  name TEXT,
  phone TEXT,
  is_online BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'offline',
  vehicle_type TEXT DEFAULT 'Road',
  verification_status TEXT DEFAULT 'approved',
  rating NUMERIC DEFAULT 5.0,
  current_latitude NUMERIC,
  current_longitude NUMERIC,
  total_earnings NUMERIC DEFAULT 0,
  total_deliveries INTEGER DEFAULT 0,
  active_points INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. RIDER CONNECTIONS TABLE (HANDSHAKE PAIRING)
CREATE TABLE IF NOT EXISTS public.rider_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  rider_id UUID REFERENCES public.rider_profiles(id) ON DELETE SET NULL,
  rider_name TEXT,
  connection_code TEXT,
  status TEXT DEFAULT 'active',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  user_id UUID,
  rider_id UUID REFERENCES public.rider_profiles(id) ON DELETE SET NULL,
  product_name TEXT,
  product_variant TEXT,
  total_price NUMERIC NOT NULL DEFAULT 0.00,
  price NUMERIC,
  status TEXT DEFAULT 'pending',
  delivery_status TEXT DEFAULT 'pending',
  payment_method TEXT DEFAULT 'cash_on_delivery',
  customer_name TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  lat NUMERIC,
  lng NUMERIC,
  merchant_rating NUMERIC,
  acceptance_message TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 6. ANNOUNCEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. CHAT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  sender_id UUID,
  sender_role TEXT, -- 'merchant', 'rider', 'customer'
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  payment_method TEXT NOT NULL, -- 'OTT', '1Voucher', 'Admin Code'
  transaction_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  payment_date TIMESTAMPTZ DEFAULT now()
);

-- 9. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 10. RIDER NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.rider_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rider_id UUID REFERENCES public.rider_profiles(id) ON DELETE CASCADE,
  shop_id BIGINT REFERENCES public.shops(id) ON DELETE SET NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'nudge',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 11. ERROR LOGGING TABLES
CREATE TABLE IF NOT EXISTS public.app_errors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  error_message TEXT,
  stack TEXT,
  context JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_error_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message TEXT,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- HIGH PERFORMANCE INDEXES FOR ZERO-LATENCY QUERIES
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_orders_shop_created_at ON public.orders(shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_rider_id ON public.orders(rider_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_menu_items_shop_id ON public.menu_items(shop_id);
CREATE INDEX IF NOT EXISTS idx_announcements_shop_id ON public.announcements(shop_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_shop_id ON public.chat_messages(shop_id);
CREATE INDEX IF NOT EXISTS idx_rider_connections_shop_id ON public.rider_connections(shop_id);
CREATE INDEX IF NOT EXISTS idx_rider_connections_rider_id ON public.rider_connections(rider_id);
CREATE INDEX IF NOT EXISTS idx_payments_shop_id ON public.payments(shop_id);

-- ==============================================================================
-- VIEWS & RPC FUNCTIONS
-- ==============================================================================
CREATE OR REPLACE VIEW public.rider_status_view AS
SELECT 
    rc.id as connection_id,
    rc.shop_id,
    rc.rider_id,
    COALESCE(rp.full_name, rc.rider_name) as rider_name,
    COALESCE(rp.is_online, false) as is_online,
    COALESCE(rp.status, 'offline') as status,
    rc.expires_at,
    rc.connection_code,
    CASE 
        WHEN rc.expires_at < now() THEN 'expired'
        WHEN rp.is_online = true THEN 'online'
        ELSE 'offline'
    END as status_derived
FROM public.rider_connections rc
LEFT JOIN public.rider_profiles rp ON rc.rider_id = rp.id;

CREATE OR REPLACE FUNCTION public.nudge_rider(rider_id UUID, message TEXT)
RETURNS VOID AS $$
DECLARE
    merchant_shop_id BIGINT;
BEGIN
    SELECT id INTO merchant_shop_id FROM public.shops WHERE owner_id::text = (SELECT auth.uid())::text LIMIT 1;
    INSERT INTO public.rider_notifications (rider_id, shop_id, message, type)
    VALUES (rider_id, merchant_shop_id, message, 'nudge');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.nudge_rider_by_id(
    target_rider_id UUID, 
    target_shop_id BIGINT, 
    nudge_message TEXT DEFAULT 'Wake up! New order incoming.'
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.rider_notifications (rider_id, shop_id, message, type)
    VALUES (target_rider_id, target_shop_id, nudge_message, 'nudge');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ==============================================================================
-- LIGHTWEIGHT, FAST ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_notifications ENABLE ROW LEVEL SECURITY;

-- Shops
CREATE POLICY "Allow public read access to shops" ON public.shops FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create shops" ON public.shops FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Merchants can update own shop" ON public.shops FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Menu Items
CREATE POLICY "Public can read menu items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Merchants can manage menu items" ON public.menu_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Orders
CREATE POLICY "Public can insert orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can view orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Authenticated users can update orders" ON public.orders FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Rider Profiles
CREATE POLICY "Riders can manage profile" ON public.rider_profiles FOR ALL USING (true) WITH CHECK (true);

-- Rider Connections
CREATE POLICY "Anyone can read rider connections" ON public.rider_connections FOR SELECT USING (true);
CREATE POLICY "Authenticated users can write rider connections" ON public.rider_connections FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Announcements
CREATE POLICY "Public read announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Authenticated manage announcements" ON public.announcements FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Chat Messages
CREATE POLICY "Chat message access" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);

-- Payments
CREATE POLICY "Payments access" ON public.payments FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Reviews
CREATE POLICY "Public read reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Public insert reviews" ON public.reviews FOR INSERT WITH CHECK (true);

-- Rider Notifications
CREATE POLICY "Rider notifications access" ON public.rider_notifications FOR ALL USING (true) WITH CHECK (true);
