import { Shop, MenuItem } from "./types";

export const MY_KOTA_SHOP: Shop = {
  id: 18,
  name: "My-Kota",
  owner_id: "ea44b2b5-7a8a-466e-8158-60e73d3e4911",
  location: "Elephant Avenue, Ivory Park, Johannesburg Ward 77, City of Johannesburg Metropolitan Municipality, 1632, South Africa",
  description: "i sell food",
  category: "Street Food",
  logo_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=300",
  rating: 4.5,
  cash_trust_enabled: false,
  allow_external_riders: true,
  auto_look_for_rider: true,
  city: "Tembisa",
  lat: -32.8791,
  lng: 27.3893,
};

export const FALLBACK_SHOPS: Shop[] = [
  MY_KOTA_SHOP,
  {
    id: 9991,
    name: "Tembisa Golden Kota Hub",
    description: "LEGENDARY multi-layered golden township kotas stacked with polony, chips, cheese, and special house sauce.",
    location: "Tembisa",
    city: "Tembisa",
    category: "Home Kitchen",
    logo_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=300",
    cash_trust_enabled: true,
    allow_external_riders: true,
    auto_look_for_rider: true,
    owner_id: null,
  },
  {
    id: 9992,
    name: "Ivory Corner Shisanyama",
    description: "Sizzling flame-grilled beef, brisket, and boerewors paired with hot chakalaka and creamy pap.",
    location: "Ivory Park",
    city: "Ivory Park",
    category: "Shisanyama",
    logo_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=300",
    cash_trust_enabled: true,
    allow_external_riders: false,
    auto_look_for_rider: false,
    owner_id: null,
  },
  {
    id: 9993,
    name: "Kaalfontein Burgers",
    description: "Smash burgers grilled to absolute juicy perfection with custom cheese and secret spices.",
    location: "Kaalfontein",
    city: "Kaalfontein",
    category: "Fast Food",
    logo_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300",
    cash_trust_enabled: false,
    allow_external_riders: true,
    auto_look_for_rider: true,
    owner_id: null,
  },
];

export const FALLBACK_MENU_ITEMS: MenuItem[] = [
  {
    id: 1801,
    shop_id: 18,
    name: "My-Kota Deluxe Quarter",
    description: "Signature township loaf loaded with crispy chips, polony, melted cheddar, Russian sausage, and secret whip.",
    price: 55.0,
    is_available: true,
    stock_quantity: 30,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    created_at: new Date().toISOString(),
  },
  {
    id: 99901,
    shop_id: 9991,
    name: "The President's Special Kota",
    description: "Triple patties, double eggs, melted cheddar layer, secret peri-peri whip, fully loaded.",
    price: 65.0,
    is_available: true,
    stock_quantity: 45,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    created_at: new Date().toISOString(),
  },
  {
    id: 99902,
    shop_id: 9991,
    name: "Classic Township Quarter Kota",
    description: "Loaded with hand-cut chips, thick polony, Russian, melted cheddar, and sweet mustard garnish.",
    price: 45.0,
    is_available: true,
    stock_quantity: 20,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    created_at: new Date().toISOString(),
  },
  {
    id: 99903,
    shop_id: 9992,
    name: "Full Brisket Platter",
    description: "Flawlessly smoked chuck beef brisket, oversized helping of pap, freshly prepared daily chakalaka.",
    price: 120.0,
    is_available: true,
    stock_quantity: 15,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    created_at: new Date().toISOString(),
  },
  {
    id: 99904,
    shop_id: 9993,
    name: "Double Cheese Kaalfontein Smash",
    description: "Two 100g beef patties smashed thin, double mature cheddar, home-pickled cucumbers on brioche.",
    price: 55.0,
    is_available: true,
    stock_quantity: 30,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    created_at: new Date().toISOString(),
  },
];
